-- 014_notifications.sql
-- Per-user notifications (Part 7). Generated by business events:
-- appointment scheduled, treatment assigned, symptom registered, etc.

CREATE TABLE IF NOT EXISTS notifications (
  id             BIGSERIAL PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  type           VARCHAR(20) NOT NULL
                 CHECK (type IN ('APPOINTMENT', 'MEDICATION', 'SYMPTOM', 'TREATMENT', 'SYSTEM')),
  title          VARCHAR(150) NOT NULL,
  message        TEXT NOT NULL,
  is_read        BOOLEAN NOT NULL DEFAULT FALSE,
  related_entity VARCHAR(50),
  related_id     BIGINT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (is_read);
